apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-aspnet-app-deployment
  labels:
    app: simple-aspnet-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-aspnet-app
  template:
    metadata:
      labels:
        app: simple-aspnet-app
    spec:
      containers:
      - name: simple-aspnet-app
        image: harbor.h3rk0.com/tests/simpleaspnetapp:v$(BUILD_NUMBER)
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: harbor-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: simple-aspnet-app
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 30000
    port: 8080
  selector:
    app: simple-aspnet-app
